name: Sync to Hugging Face Spaces
on:
  push:
    branches: [main]
    paths: ['backend/**'] # Cuma jalan kalau lu ngutak-atik isi folder backend

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to HF
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git lfs install
          git config --global user.email "haowen88yt@gmail.com"
          git config --global user.name "Adhikaxx88"
          git push https://adhikaxx88:$HF_TOKEN@huggingface.co/spaces/adhikaxx88/phishing-detection-api $(git subtree split --prefix backend main):main --force